version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - 27017:27017
    volumes:
      - ./src/docker:/docker-entrypoint-initdb.d
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: